"""create table bank_accounts and link to banks

Revision ID: 5f7bc8445564
Revises: a89ae4f429cb
Create Date: 2023-08-23 09:31:18.509112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f7bc8445564'
down_revision: Union[str, None] = 'a89ae4f429cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_accounts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('bank_id', sa.BigInteger(), nullable=False),
    sa.Column('variation', sa.Integer(), nullable=True),
    sa.Column('number', sa.String(length=64), nullable=False),
    sa.Column('type_account', sa.Enum('payment', 'saving', 'checking'), nullable=False),
    sa.Column('balance', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bank_accounts')
    # ### end Alembic commands ###
