"""create table transfer money box and link to money box

Revision ID: 724c8b22eb4d
Revises: 1c6a1dcea04b
Create Date: 2023-08-24 12:39:39.795325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '724c8b22eb4d'
down_revision: Union[str, None] = '1c6a1dcea04b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfer_money_boxes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('money_box_id', sa.BigInteger(), nullable=False),
    sa.Column('money_operation', sa.Enum('deposit', 'withdraw'), nullable=False),
    sa.Column('balance', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['money_box_id'], ['money_boxes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transfer_money_boxes')
    # ### end Alembic commands ###
