"""create table tranfer_pix and link to accounts

Revision ID: 790af9329867
Revises: 9d4d21aa55e5
Create Date: 2023-08-24 09:38:30.997167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '790af9329867'
down_revision: Union[str, None] = '9d4d21aa55e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfer_pixes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('send_pix_type', sa.Enum('mobile', 'email', 'cpf', 'cnpj', 'randomic'), nullable=False),
    sa.Column('receiver_pix_type', sa.Enum('mobile', 'email', 'cpf', 'cnpj', 'randomic'), nullable=False),
    sa.Column('is_yours', sa.Boolean(), nullable=True),
    sa.Column('send_pix_key', sa.String(length=255), nullable=False),
    sa.Column('receiver_pix_key', sa.String(length=255), nullable=False),
    sa.Column('balance', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transfer_pixes')
    # ### end Alembic commands ###
