"""create table pix and link to bank_accounts

Revision ID: 9d4d21aa55e5
Revises: eb571612c749
Create Date: 2023-08-24 09:17:02.412670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d4d21aa55e5'
down_revision: Union[str, None] = 'eb571612c749'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pixes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('bank_account_id', sa.BigInteger(), nullable=False),
    sa.Column('pix_key_type', sa.Enum('email', 'randomic', 'mobile', 'cpf', 'cnpj'), nullable=False),
    sa.Column('pix_key', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pixes')
    # ### end Alembic commands ###
