"""create table transfer pix accounts and linked to accounts

Revision ID: b006ab8456f5
Revises: bd33ac3d491a
Create Date: 2023-08-24 09:58:26.157445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b006ab8456f5'
down_revision: Union[str, None] = 'bd33ac3d491a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfer_pix_accounts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('pix_id_sender', sa.BigInteger(), nullable=False),
    sa.Column('pix_id_receiver', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['pix_id_receiver'], ['pixes.id'], ),
    sa.ForeignKeyConstraint(['pix_id_sender'], ['pixes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transfer_pix_accounts')
    # ### end Alembic commands ###
