"""table pixes pix key unique

Revision ID: bd33ac3d491a
Revises: 790af9329867
Create Date: 2023-08-24 09:41:36.638207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd33ac3d491a'
down_revision: Union[str, None] = '790af9329867'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'pixes', ['pix_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pixes', type_='unique')
    # ### end Alembic commands ###
