"""create table payments and link to accounts

Revision ID: d6b19cfd5d40
Revises: a6630ffc0011
Create Date: 2023-08-25 13:44:25.284731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd6b19cfd5d40'
down_revision: Union[str, None] = 'a6630ffc0011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('descript', sa.String(length=255), nullable=False),
    sa.Column('value_to_pay', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('signatures', 'account_id',
               existing_type=mysql.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('signatures', 'account_id',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.drop_table('payments')
    # ### end Alembic commands ###
