"""create table invoices and link to cards

Revision ID: eb571612c749
Revises: 39bde45a3bbb
Create Date: 2023-08-24 09:01:39.556432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb571612c749'
down_revision: Union[str, None] = '39bde45a3bbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('card_id', sa.BigInteger(), nullable=False),
    sa.Column('total_invoice', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('installments', sa.Integer(), nullable=False),
    sa.Column('installments_value', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('close_date', sa.Date(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoices')
    # ### end Alembic commands ###
